### PR TITLE
Simplify hyperlink interaction and layout, update tests

### LINKED ISSUE #239: Consider refactoring "ariaPressedState()" function
The function args is not even used in the function it is passed into. It just gets passed in and returned right back out without any mutations. 
```
ariaPressedState(ariaPressed) {
    const ariaToggle = function (event) {
      const ariaPressedNode = this.shadowRoot.querySelector('[aria-pressed]');
      ariaPressedNode.setAttribute("aria-pressed", 'false');

      if (event.type === 'mousedown') {
        ariaPressedNode.ariaPressed = true;
      } else {
        ariaPressedNode.ariaPressed = false;
      }

      if (event.type === 'keydown') {
        if (event.code === 'Enter' || event.code === 'Space') {
          ariaPressedNode.ariaPressed = true;
        } else {
          ariaPressedNode.ariaPressed = false;
        }
      }
    };

    // Add event listeners
    this.addEventListener('mousedown', ariaToggle);
    this.addEventListener('mouseup', ariaToggle);
    this.addEventListener('keydown', ariaToggle);
    this.addEventListener('keyup', ariaToggle);

    return ariaPressed;
  }
```

### LINKED ISSUE #332: a11y: incorrect aria toggle state
### What browser client(s) are you seeing the issue on?

- [x] Firefox
- [x] Chrome
- [x] Safari
- [x] Microsoft Edge

### What devices platform(s) are you seeing the issue on?

- [x] Desktop
- [x] Mobile

### Steps to reproduce

See code:

https://github.com/AlaskaAirlines/auro-hyperlink/blob/824be32fd59c823e6d0c695bb1668ba80b590b39/src/auro-hyperlink.js#L129-L131

This component is using `aria-pressed` incorrectly, and this should not be part of the baseline HTML structure. 

The `aria-pressed` attribute should be removed. 

**User impact**
In its current state, using `role="button"`, screen readers announce this as a `toggle button` feature. But that is confusing to an AT user because what it toggles is not clear, and the toggle state is dependent on a key-pressed state, not a toggle state. 

Additionally, it was noticed that the `spacebar` is not correctly implemented for `role="button"`, creating an additional keyboard accessibility issue.

### Expected behavior

The role of `aria-pressed` should only be used if this 'button' is being used to toggle a UI. See this ARIA-WAI example https://www.w3.org/WAI/ARIA/apg/patterns/button/examples/button/ (see the MUTE button demo).

There are other scenarios where things like `aria-expanded` and `aria-controls` would be applicable, but again, these should not be part of the native HTML template, but things that can be added via author controls. 

### Which version of auro-hyperlink do you have installed?

@latest

### Reproducible on the Auro doc site

- [x] I am able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com).

### Exit criteria (To be determined by the Auro team)

_No response_

### LINKED ISSUE #333: Extra spacing in text before referrer icon
### What browser client(s) are you seeing the issue on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What devices platform(s) are you seeing the issue on?

- [ ] Desktop
- [ ] Mobile

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Which version of auro-hyperlink do you have installed?

_No response_

### Reproducible on the Auro doc site

- [ ] I am able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com).

### Exit criteria (To be determined by the Auro team)

_No response_

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Review Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

<details>
<summary>
RC Checklist
</summary>

### Browsers

[Browsers Support Guide](https://auro.alaskaair.com/support/browsersSupport)

[Dev demo link](https://alaskaairlines.github.io/auro-hyperlink/)

Android

- [ ] Chrome
- [ ] Firefox

 iOS

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Desktop

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Scenarios

- [ ] Validated linked issues with issue reporting team
- [ ] Test coverage report review

[Framework playground ](https://github.com/AlaskaAirlines/auro-framework-playground)

- [ ] Next React
- [ ] SvelteKit

</details><br>
**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

## Summary by Sourcery

Adjust hyperlink layout and interaction behavior and update tests accordingly.

Bug Fixes:
- Resolve layout issues by changing inline hyperlink display to flex for non-CTA, non-nav types.
- Prevent test flakiness around generated absolute URLs by asserting via a port-agnostic regex match instead of a hardcoded URL string.

Enhancements:
- Remove unused ARIA pressed state handling from the base component and hyperlink markup to simplify interaction logic.

Tests:
- Update hyperlink button tests to align with removed aria-pressed behavior and new href assertion strategy.

### CODE REVIEW

**Comment by jason-capsule42** [comment]
@sourcery-ai title

File: src/component-base.mjs [hunk 1]
```diff
@@ -393,65 +393,6 @@ export default class ComponentBase extends AuroElement {
     return undefined;
   }
```
Comment (jordanjones243) [inline src/component-base.mjs:390]: `this.ariapressed` declaration needs to be removed from line 62 of this file

**Review by jordanjones243 — CHANGES_REQUESTED** [review]

**Review by jordanjones243 — CHANGES_REQUESTED** [review]
This bug from #332 needs to be addressed:
"Additionally, it was noticed that the spacebar is not correctly implemented for role="button", creating an additional keyboard accessibility issue."

**Review by jordanjones243 — APPROVED** [review]
